### ISSUE TITLE
production build problem

### ISSUE THREAD

**Issue by Ferigit** [arpitprod/charting-library-react#1]
hi, i got the project but I have a problem in production mode. when I build it and serve it i get the below error.

``
Uncaught TypeError: i.contentWindow.widgetReady is not a function
    at HTMLIFrameElement.n (charting_library.min.js:1)
``
that would nice if you have any solution for this problem.

**Comment by arpitprod** [comment]
I got this code from [here](https://github.com/tradingview/charting-library-examples/tree/master/react-javascript) 
Please go to original link and check there.
